ITEM_MAPPING = {
	[1] = {{"ProgSword", "progressive"}},

	[2] = {{"ProgSword", "toggle"}},
	[3] = {{"shield", "toggle"}},

	[4] = {{"ancientshield", "toggle"}},

	[5] = {{"Whirlwind", "toggle"}},
	[6] = {{"Bombs", "progressive"}},
	[7] = {{"Bow", "progressive"}},
	[8] = {{"bowoflight", "toggle"}},
	[9] = {{"Whip", "toggle"}},
	[10] = {{"Boomerang", "toggle"}},
	[11] = {{"SandWand", "toggle"}},
	[12] = {{"Flute", "toggle"}},

	[13] = {{"recruituniform", "toggle"}},
	[14] = {{"engineersclothes", "toggle"}},

	[15] = {{"Compass", "toggle"}},
	[16] = {{"compassoflightshard", "toggle"}},

	[17] = {{"royalengineerscertificate", "toggle"}},

	[18] = {{"Rabbit Net", "toggle"}},
	[19] = {{"stampbook", "toggle"}},
	[20] = {{"dummybow", "toggle"}},
	[21] = {{"song of awakening", "toggle"}},
	[22] = {{"Song of Healing", "toggle"}},
	[23] = {{"song of birds", "toggle"}},
	[24] = {{"song of light", "toggle"}},
	[25] = {{"song of discovery", "toggle"}},
	[26] = {{"heartcontainer", "toggle"}},
	[27] = {{"swordbeamscroll", "toggle"}},
	[28] = {{"greatspinscroll", "toggle"}},
	[29] = {{"cannon", "toggle"}},

	[30] = {{"portalunlock:hyrulecastletoanoukivillage", "toggle"}},
	[31] = {{"portalunlock:tradingposttoesnowrealm", "toggle"}},
	[32] = {{"portalunlock:deserttempletosandrealm", "toggle"}},
	[33] = {{"portalunlock:sandvalleytomarinetemple", "toggle"}},
	[34] = {{"portalunlock:forestcavetogoronvillage", "toggle"}},
	[35] = {{"portalunlock:icyspringtomountaintemple", "toggle"}},
	[36] = {{"portalunlock:mayscoretooceanportaltracks", "toggle"}},
	[37] = {{"portalunlock:snowbridgetoislandsanctuary", "toggle"}},





	[38] = {{"forest_glyph", "toggle"}},
	[39] = {{"snow_glyph", "toggle"}},
	[40] = {{"ocean_glyph", "toggle"}},
	[41] = {{"fire_glyph", "toggle"}},
	[42] = {{"wtt", "toggle"}},
	[43] = {{"btt", "toggle"}},
	[44] = {{"oct", "toggle"}},
	[45] = {{"mtt", "toggle"}},
	[46] = {{"dtt", "toggle"}},
	[47] = {{"snowdrift", "toggle"}},
	[48] = {{"slippery", "toggle"}},
	[49] = {{"pirate", "toggle"}},
	[50] = {{"las", "toggle"}},
	[51] = {{"ocean_shortcut", "toggle"}},
	[52] = {{"mayscore_bridge", "toggle"}},
	[53] = {{"tp_portal", "toggle"}},
	[54] = {{"w_castle", "toggle"}},
	[55] = {{"w_forest", "toggle"}},
	[56] = {{"cave", "toggle"}},
	[57] = {{"w_wt", "toggle"}},
	[58] = {{"n_castle", "toggle"}},
	[59] = {{"snow_bridge", "toggle"}},
	[60] = {{"nicyspring", "toggle"}},
	[61] = {{"ocean_portal", "toggle"}},

	[62] = {{"sandrealmtracks", "toggle"}},

	[63] = {{"firerealmsandportaltracks", "toggle"}},
	[64] = {{"darkoreminetracks", "toggle"}},
	[65] = {{"endsoftheearthtracks", "toggle"}},
	[66] = {{"disorientationstationtracks", "toggle"}},
	[67] = {{"snowrealmgorgetracks", "toggle"}},

	[68] = {{"forest_source", "toggle"}},
	[69] = {{"snow_source", "toggle"}},
	[70] = {{"ocean_source", "toggle"}},
	[71] = {{"fire_source", "toggle"}},
	[72] = {{"sandsource", "toggle"}},

 



	[73] = {{"grassrabbit", "toggle"}},
	[74] = {{"snowrabbit", "toggle"}},
	[75] = {{"oceanrabbit", "toggle"}},
	[76] = {{"mountainrabbit", "toggle"}},
	[77] = {{"sandrabbit", "toggle"}},

	[78] = {{"grassrabbits(2)", "toggle"}},
	[79] = {{"snowrabbits(2)", "toggle"}},
	[80] = {{"oceanrabbits(2)", "toggle"}},
	[81] = {{"mountainrabbits(2)", "toggle"}},
	[82] = {{"sandrabbits(2)", "toggle"}},

	[83] = {{"grassrabbits(3)", "toggle"}},
	[84] = {{"snowrabbits(3)", "toggle"}},
	[85] = {{"oceanrabbits(3)", "toggle"}},
	[86] = {{"mountainrabbits(3)", "toggle"}},
	[87] = {{"sandrabbits(3)", "toggle"}},

	[88] = {{"grassrabbits(4)", "toggle"}},
	[89] = {{"snowrabbits(4)", "toggle"}},
	[90] = {{"oceanrabbits(4)", "toggle"}},
	[91] = {{"mountainrabbits(4)", "toggle"}},
	[92] = {{"sandrabbits(4)", "toggle"}},

	[93] = {{"grassrabbits(5)", "toggle"}},
	[94] = {{"snowrabbits(5)", "toggle"}},
	[95] = {{"oceanrabbits(5)", "toggle"}},
	[96] = {{"mountainrabbits(5)", "toggle"}},
	[97] = {{"sandrabbits(5)", "toggle"}},

	[98] = {{"grassrabbits(10)", "toggle"}},
	[99] = {{"snowrabbits(10)", "toggle"}},
	[100] = {{"oceanrabbits(10)", "toggle"}},
	[101] = {{"mountainrabbits(10)", "toggle"}},
	[102] = {{"sandrabbits(10)", "toggle"}},

    -- Treasures	
	[118] = {{"treasure:demonfossil", "toggle"}},
	[119] = {{"treasure:stalfosskull", "toggle"}},
	[120] = {{"treasure:starfragment", "toggle"}},
	[121] = {{"treasure:beelarvae", "toggle"}},
	[122] = {{"treasure:woodheart", "toggle"}},
	[123] = {{"treasure:darkpearlloop", "toggle"}},
	[124] = {{"treasure:whitepearlloop", "toggle"}},
	[125] = {{"treasure:rutocrown", "toggle"}},
	[126] = {{"treasure:dragonscale", "toggle"}},
	[127] = {{"treasure:piratesnecklace", "toggle"}},
	[128] = {{"treasure:palacedish", "toggle"}},
	[129] = {{"treasure:goronamber", "toggle"}},
	[130] = {{"treasure:mysticjade", "toggle"}},
	[131] = {{"treasure:ancientcoin", "toggle"}},
	[132] = {{"treasure:pricelessstone", "toggle"}},
	[133] = {{"treasure:regalring", "toggle"}},

    -- Keys
	[134] = {{"TunnelSmall", "toggle"}},
	[135] = {{"WoodSmall", "toggle"}},
	[146] = {{"BlizzSmall", "toggle"}},
	[148] = {{"Marinemall", "toggle"}},
	[150] = {{"MountSmall", "toggle"}},
	[152] = {{"DesSmall", "toggle"}},

	[137] = {{"smallkey(tos) I dunno what this is actually", "toggle"}},
	[138] = {{"ToS2Small", "toggle"}},
	[140] = {{"Tos4Small", "toggle"}},
	[142] = {{"ToS5Small", "toggle"}},
	[144] = {{"ToS6Small", "toggle"}},

	[154] = {{"WoodBig", "toggle"}},
	[155] = {{"BlizzBig", "toggle"}},
	[156] = {{"MarinBig", "toggle"}},
	[157] = {{"MountBig", "toggle"}},
	[158] = {{"DesBig", "toggle"}},
	[159] = {{"ToS3Big", "toggle"}},
	[160] = {{"Tos5Big", "toggle"}},

	[161] = {{"SnurglarKeys", "toggle"}},
	[165] = {{"SnurglarKeys", "toggle"}},

    --Key Rings
	[136] = {{"WoodSmall", "toggle"}},
	[139] = {{"ToS2Small", "toggle"}},
	[141] = {{"Tos4Small", "toggle"}},
	[143] = {{"ToS5Small", "toggle"}},
	[145] = {{"ToS6Small", "toggle"}},
	[147] = {{"BlizzSmall", "toggle"}},
	[149] = {{"Marinemall", "toggle"}},
	[151] = {{"MountSmall", "toggle"}},
	[153] = {{"DesSmall", "toggle"}},







	[166] = {{"tearoflight", "toggle"}},
	[167] = {{"tearoflight(tos1)", "toggle"}},
	[168] = {{"tearoflight(tos2)", "toggle"}},
	[169] = {{"tearoflight(tos3)", "toggle"}},
	[170] = {{"tearoflight(tos4)", "toggle"}},
	[171] = {{"tearoflight(tos5)", "toggle"}},
	[172] = {{"tearoflight(tos6)", "toggle"}},
	[173] = {{"tearoflight(allsections)", "toggle"}},
	[174] = {{"tearoflight(progressive)", "toggle"}},
	[175] = {{"bigtearoflight(tos1)", "toggle"}},
	[176] = {{"bigtearoflight(tos2)", "toggle"}},
	[177] = {{"bigtearoflight(tos3)", "toggle"}},
	[178] = {{"bigtearoflight(tos4)", "toggle"}},
	[179] = {{"bigtearoflight(tos5)", "toggle"}},
	[180] = {{"bigtearoflight(tos6)", "toggle"}},
	[181] = {{"bigtearoflight(progressive)", "toggle"}},
	[182] = {{"bigtearoflight(allsections)", "toggle"}},
	[183] = {{"train:brighttrain", "toggle"}},
	[184] = {{"train:irontrain", "toggle"}},
	[185] = {{"train:stonetrain", "toggle"}},
	[186] = {{"train:vintagetrain", "toggle"}},
	[187] = {{"train:demontrain", "toggle"}},
	[188] = {{"train:tropicaltrain", "toggle"}},
	[189] = {{"train:dignifiedtrain", "toggle"}},
	[190] = {{"train:goldentrain", "toggle"}},
	[191] = {{"_ut_glitched_logic", "toggle"}},
	[192] = {{"towerofspiritsbase", "toggle"}},
	[193] = {{"progressivetossection", "toggle"}},
	[194] = {{"repairtradingpostbridge", "toggle"}},
	[195] = {{"snowfallsanctuarycavekey", "toggle"}},
	[196] = {{"prizepostcards(10)", "toggle"}},
	[197] = {{"wagon", "toggle"}},

	[198] = {{"Passenger Kenzo", "toggle"}},
	[199] = {{"Passenger Kenzo", "toggle"}},
	[200] = {{"Passenger Joe", "toggle"}},
	[201] = {{"Passenger Noko", "toggle"}},
	[202] = {{"Passenger Mona", "toggle"}},
	[203] = {{"Passenger Ferrus", "toggle"}},
	[204] = {{"Passenger Alfonzo", "toggle"}},
	[205] = {{"Passenger Dovok", "toggle"}},
	[206] = {{"Passenger Snow Goron", "toggle"}},
	[207] = {{"Passenger City Goron", "toggle"}},
	[208] = {{"passenger:teacher", "toggle"}},
	[209] = {{"Passenger Kofu", "toggle"}},
	[210] = {{"Passenger Carben", "toggle"}},
	[211] = {{"Passenger Wadatsumi", "toggle"}},
	[212] = {{"passenger:wood", "toggle"}},
	[213] = {{"passenger:morris", "toggle"}},
	[214] = {{"passenger:yamahiko", "toggle"}},
	[215] = {{"passenger:mash", "toggle"}},

	[216] = {{"cargo:lumber", "toggle"}},
	[217] = {{"cargo:megaice", "toggle"}},
	[218] = {{"cargo:goronsteel", "toggle"}},
	[219] = {{"cargo:fish", "toggle"}},
	[220] = {{"cargo:vessel", "toggle"}},
	[221] = {{"Cargo: Cuccos", "toggle"}},
	[222] = {{"Cargo: Cuccos", "toggle"}},
	[223] = {{"cargo:darkore", "toggle"}},

	
	[224] = {{"Stamp: Castle Town", "toggle"}},
	[225] = {{"Stamp: Outset Village", "toggle"}},
	[226] = {{"Stamp: Mayscore", "toggle"}},
	[227] = {{"Stamp: Woodland Sanctuary", "toggle"}},
	[228] = {{"Stamp: Anouki Village", "toggle"}},
	[229] = {{"Stamp: Snowfall Sanctuary", "toggle"}},
	[230] = {{"Stamp: Papuzia Village", "toggle"}},
	[231] = {{"Stamp: Island Sanctuary", "toggle"}},
	[232] = {{"Stamp: Goron Village", "toggle"}},
	[233] = {{"Stamp: Valley Sanctuary", "toggle"}},
	[234] = {{"Stamp: Dune Sanctuary", "toggle"}},
	[235] = {{"Stamp: Wooded Temple", "toggle"}},
	[236] = {{"Stamp: Blizzard Temple", "toggle"}},
	[237] = {{"Stamp: Marine Temple", "toggle"}},
	[238] = {{"Stamp: Mountain Temple", "toggle"}},
	[239] = {{"Stamp: Desert Temple", "toggle"}},
	[240] = {{"Stamp: Pirate Hideout", "toggle"}},
	[241] = {{"Stamp: Trading Post", "toggle"}},
	[242] = {{"Stamp: Icy Spring", "toggle"}},
	[243] = {{"Stamp: Tower of Spirits", "toggle"}},
	[244] = {{"stamppack(2)", "toggle"}},
	[245] = {{"stamppack(3)", "toggle"}},
	[246] = {{"stamppack(4)", "toggle"}},
	[247] = {{"stamppack(5)", "toggle"}},




	[248] = {{"westernforesttracks", "toggle"}},
	[249] = {{"anoukivillagetracks", "toggle"}},
	[250] = {{"thawlandtracks", "toggle"}},
	[251] = {{"blizzardtracks", "toggle"}},
	[252] = {{"castletracks", "toggle"}},
	[253] = {{"woodlandtracks", "toggle"}},
	[254] = {{"borderlandstracks", "toggle"}},
	[255] = {{"coastaltracks", "toggle"}},
	[256] = {{"piratetracks", "toggle"}},
	[257] = {{"oceantracks", "toggle"}},
	[258] = {{"islandtracks", "toggle"}},
	[259] = {{"valleytracks", "toggle"}},
	[260] = {{"mountaintracks", "toggle"}},
	[261] = {{"aridtracks", "toggle"}},
	[262] = {{"dunetracks", "toggle"}},
	[263] = {{"towertracks", "toggle"}},
	[264] = {{"completedforestglyph", "toggle"}},
	[265] = {{"majorforesttracks", "toggle"}},
	[266] = {{"minorforesttracks", "toggle"}},
	[267] = {{"completedsnowglyph", "toggle"}},
	[268] = {{"majorsnowtracks", "toggle"}},
	[269] = {{"minorsnowtracks", "toggle"}},
	[270] = {{"completedoceanglyph", "toggle"}},
	[271] = {{"majoroceantracks", "toggle"}},
	[272] = {{"minoroceantracks", "toggle"}},
	[273] = {{"completedfireglyph", "toggle"}},
	[274] = {{"majorfiretracks", "toggle"}},
	[275] = {{"minorfiretracks", "toggle"}},
	[276] = {{"completeddeserttracks", "toggle"}},
	[277] = {{"majordeserttracks", "toggle"}},
	[278] = {{"minordeserttracks", "toggle"}}
}