-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
LOCATION_MAPPING = {
    [2] = {"@Aquas/Mission Complete"},
    [3] = {"@Aquas/Medal"},
    [4] = {"@Aquas/Checkpoint"},

    [5] = {"@Area 6/Mission Complete"},
    [6] = {"@Area 6/Medal"},
    [7] = {"@Area 6/Below Early Defense Station: Gold Ring"},
    [8] = {"@Area 6/Above Early Defense Station: Laser Upgrade"},
    [9] = {"@Area 6/Andross' Taunt: Gold Ring"},
    [10] = {"@Area 6/Checkpoint"},
    [11] = {"@Area 6/Near Defense Station After Checkpoint: Gold Ring"},

    [12] = {"@Bolse/Mission Complete"},
    [13] = {"@Bolse/Medal"},

    [14] = {"@Corneria/Mission Complete"},
    [15] = {"@Corneria/Mission Accomplished"},
    [16] = {"@Corneria/Medal"},
    [17] = {"@Corneria/Under Arch: Gold Ring"},
    [18] = {"@Corneria/Behind Doors: Bomb"},
    [19] = {"@Corneria/Center of Corneria City: Silver Ring"},
    [20] = {"@Corneria/Near First Ground Robot: Laser Upgrade"},
    [21] = {"@Corneria/Under Highway Arch: Gold Ring"},
    [22] = {"@Corneria/Behind Second Ground Robot: Bomb"},
    [23] = {"@Corneria/Behind Doors Near Checkpoint: Gold Ring"},
    [24] = {"@Corneria/Checkpoint"},
    [25] = {"@Corneria/After Falco's G-Diffuser Issue: Laser Upgrade"},
    [26] = {"@Corneria/After Falco's G-Diffuser Issue: Bomb"},
    [27] = {"@Corneria/Water Section Last Arch: Gold Ring"},
    [28] = {"@Corneria/Left of Waterfall: Laser Upgrade"},
    [29] = {"@Corneria/Before Mission Complete Boss, Lower: Gold Ring"},
    [30] = {"@Corneria/Before Mission Complete Boss, Upper: Gold Ring"},

    [31] = {"@Fortuna/Mission Complete"},
    [32] = {"@Fortuna/Mission Accomplished"},
    [33] = {"@Fortuna/Medal"},

    [34] = {"@Katina/Mission Complete"},
    [35] = {"@Katina/Mission Accomplished"},
    [36] = {"@Katina/Medal"},

    [37] = {"@Macbeth/Mission Complete"},
    [38] = {"@Macbeth/Mission Accomplished"},
    [39] = {"@Macbeth/Medal"},
    [40] = {"@Macbeth/Before Hill With Rolling Rocks: Bomb"},
    [41] = {"@Macbeth/Above Rolling Rocks: Gold Ring"},
    [42] = {"@Macbeth/On Tracks Before Bridge: Gold Ring"},
    [43] = {"@Macbeth/On Tracks After Bridge: Gold Ring"},
    [44] = {"@Macbeth/Checkpoint"},
    [45] = {"@Macbeth/After First Building: Silver Ring"},
    [46] = {"@Macbeth/Before Buildings Three And Four: Silver Ring"},
    [47] = {"@Macbeth/After Buildings Three And Four, Right: Silver Ring"},
    [48] = {"@Macbeth/Before Building Five: Silver Ring"},
    [49] = {"@Macbeth/After Building Five: Gold Ring"},
    [50] = {"@Macbeth/Under Bridge After Checkpoint: Bomb"},
    [51] = {"@Macbeth/First Building After Switcher: Gold Ring"},
    [52] = {"@Macbeth/Second Building After Switcher: Silver Ring"},
    [53] = {"@Macbeth/After Marker 100: Silver Ring"},
    [54] = {"@Macbeth/Before Marker 300: Silver Ring"},

    [55] = {"@Meteo/Mission Complete"},
    [56] = {"@Meteo/Warp"},
    [57] = {"@Meteo/Medal"},
    [58] = {"@Meteo/After Starting Asteroids: Gold Ring"},
    [59] = {"@Meteo/End Of First Tunnel, Top: Silver Ring"},
    [60] = {"@Meteo/End Of First Tunnel, Middle: Gold Ring"},
    [61] = {"@Meteo/End Of First Tunnel, Bottom: Bomb"},
    [62] = {"@Meteo/Between Two Big Asteroids: Bomb"},
    [63] = {"@Meteo/Checkpoint"},
    [64] = {"@Meteo/Near Warp Rings: Gold Ring"},
    [65] = {"@Meteo/Just Before Boss: Gold Ring"},

    [66] = {"@Sector X/Mission Complete"},
    [67] = {"@Sector X/Mission Accomplished"},
    [68] = {"@Sector X/Warp"},
    [69] = {"@Sector X/Medal"},
    [70] = {"@Sector X/In Debris Field, Left: Gold Ring"},
    [71] = {"@Sector X/Checkpoint"},
    [72] = {"@Sector X/Behind Enemy After Peppy Gets Chased, Right: Gold Ring"},
    [73] = {"@Sector X/Left Path - Just After Fork, Through Bottom Slot: Laser Upgrade"},
    [74] = {"@Sector X/Left Path - Closing Door Section: Gold Ring"},
    [75] = {"@Sector X/Left Path - After Closing Door Section: Bomb"},
    [76] = {"@Sector X/Left Path - Behind First Warp Gate: Gold Ring"},
    [77] = {"@Sector X/Left Path - After First Warp Gate, Up High: Bomb"},
    [78] = {"@Sector X/Left Path - Before Final Warp Gate: Gold Ring"},

    [79] = {"@Sector Y/Mission Complete"},
    [80] = {"@Sector Y/Mission Accomplished"},
    [81] = {"@Sector Y/Medal"},
    [82] = {"@Sector Y/Above Friendly Ship Near Start: Gold Ring"},
    [83] = {"@Sector Y/Before Checkpoint: Gold Ring"},
    [84] = {"@Sector Y/Checkpoint"},
    [85] = {"@Sector Y/Breaking Through The Enemy Fleet: Beginning: Gold Ring"},
    [86] = {"@Sector Y/Breaking Through The Enemy Fleet: Middle: Gold Ring"},
    [87] = {"@Sector Y/Breaking Through The Enemy Fleet: End: Gold Ring"},

    [88] = {"@Sector Z/Mission Complete"},
    [89] = {"@Sector Z/Mission Accomplished"},
    [90] = {"@Sector Z/Medal"},

    [91] = {"@Solar/Mission Complete"},
    [92] = {"@Solar/Medal"},
    [93] = {"@Solar/Checkpoint"},

    [94] = {"@Titania/Mission Complete"},
    [95] = {"@Titania/Medal"},
    [96] = {"@Titania/Second Falling Tower From Start: Bomb"},
    [97] = {"@Titania/Through Two Leaning Towers: Gold Ring"},
    [98] = {"@Titania/After Three Bone Structures: Bomb"},
    [99] = {"@Titania/Above Skull: Silver Ring"},
    [100] = {"@Titania/On Bridge: Gold Ring"},
    [101] = {"@Titania/Right Of Bridge: Gold Ring"},
    [102] = {"@Titania/Upper Left Path: Bomb"},
    [103] = {"@Titania/Suspended Above Two Bridges: Silver Ring"},
    [104] = {"@Titania/Checkpoint"},
    [105] = {"@Titania/Falling Towers Section: First Bomb"},
    [106] = {"@Titania/Falling Towers Section: Gold Ring"},
    [107] = {"@Titania/Falling Towers Section: Second Bomb"},
    [108] = {"@Titania/Falling Towers Section: Third Bomb"},
    [109] = {"@Titania/Behind Arches On The Right: Gold Ring"},
    [110] = {"@Titania/Upper Right Hill: Gold Ring"},
    [111] = {"@Titania/First Falling Tower Before Boss: Silver Ring"},
    [112] = {"@Titania/First Falling Tower Before Boss: Gold Ring"},
    [113] = {"@Titania/Second Falling Tower Before Boss: Silver Ring"},
    [114] = {"@Titania/Second Falling Tower Before Boss: Gold Ring"},
    
    [115] = {"@Venom/Medal"},
    [116] = {"@Goal/Defeat Robot Andross"},
    [117] = {"@Venom/Venom 1 - Near Start, Bottom: Gold Ring"},
    [118] = {"@Venom/Venom 1 - Near Start, Top: Laser Upgrade"},
    [119] = {"@Venom/Venom 1 - Maze (R R R): Gold Ring"},
    [120] = {"@Venom/Venom 1 - Maze (L L): Gold Ring"},
    [121] = {"@Venom/Venom 1 - Maze (R R L L): Gold Ring"},
    [122] = {"@Venom/Venom 1 - End Of Maze (R R R R): Gold Ring"},
    [123] = {"@Venom/Venom 1 - End Of Maze (L L L): Gold Ring"},
    [124] = {"@Venom/Venom 1 - End Of Maze (R R L L): Gold Ring"},
    [125] = {"@Venom/Venom 1 - Checkpoint"},
    [126] = {"@Goal/Defeat Andross"},

    [127] = {"@Zoness/Mission Complete"},
    [128] = {"@Zoness/Mission Accomplished"},
    [129] = {"@Zoness/Medal"},
    [130] = {"@Zoness/Before Katt Appears, Top: Gold Ring"},
    [131] = {"@Zoness/Before Katt Appears, Middle: Silver Ring"},
    [132] = {"@Zoness/Before Katt Appears, Bottom: Bomb"},
    [133] = {"@Zoness/Checkpoint"},
    [134] = {"@Zoness/Aim For The Rudder, First Gate: Laser Upgrade"},
    [135] = {"@Zoness/Aim For The Rudder, Second Gate, Left: Bomb"},
    [136] = {"@Zoness/Aim For The Rudder, Third Gate: Silver Ring"}
}
