Tracker:AddLocations("locations/Anouki Village Bomb Cave Chest.json")
Tracker:AddLocations("locations/Anouki Village Fence Progress Gift.json")
Tracker:AddLocations("locations/Anouki Village Goron Force Gem.json")
Tracker:AddLocations("locations/Anouki Village Lake Chest.json")
Tracker:AddLocations("locations/Anouki Village Pair Villagers.json")
Tracker:AddLocations("locations/Anouki Village Pick Up Kofu.json")
Tracker:AddLocations("locations/Anouki Village Pick Up Noko.json")
Tracker:AddLocations("locations/Anouki Village Repair Fence.json")
Tracker:AddLocations("locations/Anouki Village Song Statue.json")
Tracker:AddLocations("locations/Anouki Village Song Statue Chest.json")
Tracker:AddLocations("locations/Anouki Village Stamp Station.json")
Tracker:AddLocations("locations/Beedle Joes Force Gem.json")
Tracker:AddLocations("locations/Beedle Shop Bomb Bag.json")
Tracker:AddLocations("locations/Beedle Shop Bomb Refill.json")
Tracker:AddLocations("locations/Beedle Shop Purple Potion.json")
Tracker:AddLocations("locations/Beedle Shop Rare Treasure.json")
Tracker:AddLocations("locations/Beedle Shop Red Potion.json")
Tracker:AddLocations("locations/Beedle Shop Uncommon Treasure.json")
Tracker:AddLocations("locations/Blizzard Temple 1F NE Chest.json")
Tracker:AddLocations("locations/Blizzard Temple 1F NW Chest.json")
Tracker:AddLocations("locations/Blizzard Temple 1F Torch Chest.json")
Tracker:AddLocations("locations/Blizzard Temple 2F Boss Key.json")
Tracker:AddLocations("locations/Blizzard Temple B1 E Enemy Chest.json")
Tracker:AddLocations("locations/Blizzard Temple B1 NE Enemy Chest.json")
Tracker:AddLocations("locations/Blizzard Temple B1 NW Enemy Chest.json")
Tracker:AddLocations("locations/Blizzard Temple B1 SE Chest.json")
Tracker:AddLocations("locations/Blizzard Temple B1 SW Chest.json")
Tracker:AddLocations("locations/Blizzard Temple B1 Stamp Station.json")
Tracker:AddLocations("locations/Blizzard Temple Boss Heart Container.json")
Tracker:AddLocations("locations/Blizzard Temple Dungeon Reward.json")
Tracker:AddLocations("locations/Bridge Workers Home Buried Chest.json")
Tracker:AddLocations("locations/Bridge Workers Home Pick Up Kenzo.json")
Tracker:AddLocations("locations/Castle Town Buy Cuccos.json")
Tracker:AddLocations("locations/Castle Town Deliver Fish.json")
Tracker:AddLocations("locations/Castle Town Empty House Roof Chest.json")
Tracker:AddLocations("locations/Castle Town Goron Force Gem.json")
Tracker:AddLocations("locations/Castle Town Left Wall Chest.json")
Tracker:AddLocations("locations/Castle Town Minigame Roof.json")
Tracker:AddLocations("locations/Castle Town Pick Up Alfonzo.json")
Tracker:AddLocations("locations/Castle Town Pick Up Mona.json")
Tracker:AddLocations("locations/Castle Town Pick Up Teacher.json")
Tracker:AddLocations("locations/Castle Town Ramp House Chest.json")
Tracker:AddLocations("locations/Castle Town Right Wall Chest.json")
Tracker:AddLocations("locations/Castle Town Shop Postcards.json")
Tracker:AddLocations("locations/Castle Town Shop Red Potion.json")
Tracker:AddLocations("locations/Castle Town Shop Shield.json")
Tracker:AddLocations("locations/Castle Town Shop Treasure 1.json")
Tracker:AddLocations("locations/Castle Town Shop Treasure 2.json")
Tracker:AddLocations("locations/Castle Town Stamp Station.json")
Tracker:AddLocations("locations/Castle Town Take em All On Level 1.json")
Tracker:AddLocations("locations/Castle Town Take em All On Level 2.json")
Tracker:AddLocations("locations/Castle Town Take em All On Level 3.json")
Tracker:AddLocations("locations/Castle Town Take em All On Level 3 Capbone Chest.json")
Tracker:AddLocations("locations/Catch 1 Grass Rabbit.json")
Tracker:AddLocations("locations/Catch 1 Mountain Rabbit.json")
Tracker:AddLocations("locations/Catch 1 Ocean Rabbit.json")
Tracker:AddLocations("locations/Catch 1 Sand Rabbit.json")
Tracker:AddLocations("locations/Catch 1 Snow Rabbit.json")
Tracker:AddLocations("locations/Catch 10 Grass Rabbits.json")
Tracker:AddLocations("locations/Catch 10 Mountain Rabbits.json")
Tracker:AddLocations("locations/Catch 10 Ocean Rabbits.json")
Tracker:AddLocations("locations/Catch 10 Sand Rabbits.json")
Tracker:AddLocations("locations/Catch 10 Snow Rabbits.json")
Tracker:AddLocations("locations/Catch 2 Grass Rabbits.json")
Tracker:AddLocations("locations/Catch 2 Mountain Rabbits.json")
Tracker:AddLocations("locations/Catch 2 Ocean Rabbits.json")
Tracker:AddLocations("locations/Catch 2 Sand Rabbits.json")
Tracker:AddLocations("locations/Catch 2 Snow Rabbits.json")
Tracker:AddLocations("locations/Catch 3 Grass Rabbits.json")
Tracker:AddLocations("locations/Catch 3 Mountain Rabbits.json")
Tracker:AddLocations("locations/Catch 3 Ocean Rabbits.json")
Tracker:AddLocations("locations/Catch 3 Sand Rabbits.json")
Tracker:AddLocations("locations/Catch 3 Snow Rabbits.json")
Tracker:AddLocations("locations/Catch 4 Grass Rabbits.json")
Tracker:AddLocations("locations/Catch 4 Mountain Rabbits.json")
Tracker:AddLocations("locations/Catch 4 Ocean Rabbits.json")
Tracker:AddLocations("locations/Catch 4 Sand Rabbits.json")
Tracker:AddLocations("locations/Catch 4 Snow Rabbits.json")
Tracker:AddLocations("locations/Catch 5 Grass Rabbits.json")
Tracker:AddLocations("locations/Catch 5 Mountain Rabbits.json")
Tracker:AddLocations("locations/Catch 5 Ocean Rabbits.json")
Tracker:AddLocations("locations/Catch 5 Sand Rabbits.json")
Tracker:AddLocations("locations/Catch 5 Snow Rabbits.json")
Tracker:AddLocations("locations/Catch 6 Grass Rabbits.json")
Tracker:AddLocations("locations/Catch 6 Mountain Rabbits.json")
Tracker:AddLocations("locations/Catch 6 Ocean Rabbits.json")
Tracker:AddLocations("locations/Catch 6 Sand Rabbits.json")
Tracker:AddLocations("locations/Catch 6 Snow Rabbits.json")
Tracker:AddLocations("locations/Catch 7 Grass Rabbits.json")
Tracker:AddLocations("locations/Catch 7 Mountain Rabbits.json")
Tracker:AddLocations("locations/Catch 7 Ocean Rabbits.json")
Tracker:AddLocations("locations/Catch 7 Sand Rabbits.json")
Tracker:AddLocations("locations/Catch 7 Snow Rabbits.json")
Tracker:AddLocations("locations/Catch 8 Grass Rabbits.json")
Tracker:AddLocations("locations/Catch 8 Mountain Rabbits.json")
Tracker:AddLocations("locations/Catch 8 Ocean Rabbits.json")
Tracker:AddLocations("locations/Catch 8 Sand Rabbits.json")
Tracker:AddLocations("locations/Catch 8 Snow Rabbits.json")
Tracker:AddLocations("locations/Catch 9 Grass Rabbits.json")
Tracker:AddLocations("locations/Catch 9 Mountain Rabbits.json")
Tracker:AddLocations("locations/Catch 9 Ocean Rabbits.json")
Tracker:AddLocations("locations/Catch 9 Sand Rabbits.json")
Tracker:AddLocations("locations/Catch 9 Snow Rabbits.json")
Tracker:AddLocations("locations/Dark Ore Mine Buried Chest.json")
Tracker:AddLocations("locations/Dark Ore Mine Buy Ore.json")
Tracker:AddLocations("locations/Desert Temple 1F Entrance Chest.json")
Tracker:AddLocations("locations/Desert Temple 1F N Arena Chest.json")
Tracker:AddLocations("locations/Desert Temple 1F N Arena Stalfos Skull.json")
Tracker:AddLocations("locations/Desert Temple 1F N Buried Key.json")
Tracker:AddLocations("locations/Desert Temple 1F N Ergtorok Chest.json")
Tracker:AddLocations("locations/Desert Temple 1F N Trap Chest.json")
Tracker:AddLocations("locations/Desert Temple 1F NW Gerune Chest.json")
Tracker:AddLocations("locations/Desert Temple 2F Left Chest.json")
Tracker:AddLocations("locations/Desert Temple 2F Right Chest.json")
Tracker:AddLocations("locations/Desert Temple 3F Chest.json")
Tracker:AddLocations("locations/Desert Temple B1 Boss Key.json")
Tracker:AddLocations("locations/Desert Temple B1 NW Buried Rupee.json")
Tracker:AddLocations("locations/Desert Temple B1 Near Boss Door Chest.json")
Tracker:AddLocations("locations/Desert Temple B1 SW Stalfos Chest.json")
Tracker:AddLocations("locations/Desert Temple B1 Stamp Station.json")
Tracker:AddLocations("locations/Desert Temple Boss Heart Container.json")
Tracker:AddLocations("locations/Desert Temple Bow of Light Chest.json")
Tracker:AddLocations("locations/Desert Temple Dungeon Reward.json")
Tracker:AddLocations("locations/Disorientation Station Bird Chest.json")
Tracker:AddLocations("locations/Disorientation Station Cliff Chest.json")
Tracker:AddLocations("locations/Disorientation Station Climb Chest.json")
Tracker:AddLocations("locations/Disorientation Station Guard Gift.json")
Tracker:AddLocations("locations/Disorientation Station Maze Chest.json")
Tracker:AddLocations("locations/Dune Sanctuary Deliver Cuccos.json")
Tracker:AddLocations("locations/Dune Sanctuary Song of Restoration.json")
Tracker:AddLocations("locations/Dune Sanctuary Stamp Station.json")
Tracker:AddLocations("locations/Ends of the Earth Golden Big Chest.json")
Tracker:AddLocations("locations/Ends of the Earth Golden Small Chest.json")
Tracker:AddLocations("locations/Ends of the Earth Master Big Chest.json")
Tracker:AddLocations("locations/Ends of the Earth Master Small Chest.json")
Tracker:AddLocations("locations/Ends of the Earth Tempered Big Chest.json")
Tracker:AddLocations("locations/Ends of the Earth Tempered Small Chest.json")
Tracker:AddLocations("locations/Fire Realm Pick Up Ferrus.json")
Tracker:AddLocations("locations/Fire Realm Shoot Sand Portal.json")
Tracker:AddLocations("locations/Forest Realm Ferrus Gift.json")
Tracker:AddLocations("locations/Forest Realm Shoot Cave Portal.json")
Tracker:AddLocations("locations/Forest Realm Shoot SE Portal.json")
Tracker:AddLocations("locations/Goron Shop Bomb Refill.json")
Tracker:AddLocations("locations/Goron Shop Postcards.json")
Tracker:AddLocations("locations/Goron Shop Purple Potion.json")
Tracker:AddLocations("locations/Goron Shop Quiver.json")
Tracker:AddLocations("locations/Goron Shop Shield.json")
Tracker:AddLocations("locations/Goron Shop Yellow Potion.json")
Tracker:AddLocations("locations/Goron Target Range.json")
Tracker:AddLocations("locations/Goron Village Chest Above Elders House.json")
Tracker:AddLocations("locations/Goron Village Deliver Ice Force Gem.json")
Tracker:AddLocations("locations/Goron Village Get Wagon.json")
Tracker:AddLocations("locations/Goron Village Kofu Force Gem.json")
Tracker:AddLocations("locations/Goron Village Pick Up City Goron.json")
Tracker:AddLocations("locations/Goron Village Pick Up Snow Goron.json")
Tracker:AddLocations("locations/Goron Village West Buy Steel.json")
Tracker:AddLocations("locations/Goron Village West Center Chest.json")
Tracker:AddLocations("locations/Goron Village West NE Chest.json")
Tracker:AddLocations("locations/Goron Village West Stamp Station.json")
Tracker:AddLocations("locations/Goron Village West Steel Chest.json")
Tracker:AddLocations("locations/Hyrule Castle 1F Back Chest.json")
Tracker:AddLocations("locations/Hyrule Castle 1F Sword Minigame 60 Points.json")
Tracker:AddLocations("locations/Hyrule Castle 2F Indoors Chest.json")
Tracker:AddLocations("locations/Hyrule Castle 3F Spirit Flute.json")
Tracker:AddLocations("locations/Hyrule Castle Exterior NW Chest.json")
Tracker:AddLocations("locations/Icy Spring Buy Mega Ice.json")
Tracker:AddLocations("locations/Icy Spring Nokos Force Gem.json")
Tracker:AddLocations("locations/Icy Spring Stamp Station.json")
Tracker:AddLocations("locations/Icy Spring Whip Chest.json")
Tracker:AddLocations("locations/Island Sanctuary Carbens Force Gem.json")
Tracker:AddLocations("locations/Island Sanctuary Cucco Chest.json")
Tracker:AddLocations("locations/Island Sanctuary NW Chest.json")
Tracker:AddLocations("locations/Island Sanctuary S Island Chest.json")
Tracker:AddLocations("locations/Island Sanctuary Song of Restoration.json")
Tracker:AddLocations("locations/Island Sanctuary Stamp Station.json")
Tracker:AddLocations("locations/Lost at Sea Buried Chest.json")
Tracker:AddLocations("locations/Lost at Sea Final Challenge NE Chest.json")
Tracker:AddLocations("locations/Lost at Sea Final Challenge NW Chest.json")
Tracker:AddLocations("locations/Lost at Sea Final Challenge SE Chest.json")
Tracker:AddLocations("locations/Lost at Sea Final Challenge SW Chest.json")
Tracker:AddLocations("locations/Lost at Sea Final Chest.json")
Tracker:AddLocations("locations/Lost at Sea Plain Phantom Chest.json")
Tracker:AddLocations("locations/Lost at Sea Torch Phantom Chest.json")
Tracker:AddLocations("locations/Lost at Sea Warp Phantom Chest.json")
Tracker:AddLocations("locations/Lost at Sea Wrecker Phantom NE Chest.json")
Tracker:AddLocations("locations/Lost at Sea Wrecker Phantom SW Chest.json")
Tracker:AddLocations("locations/Marine Temple 1F Lever Chest.json")
Tracker:AddLocations("locations/Marine Temple 1F Vines Chest.json")
Tracker:AddLocations("locations/Marine Temple 2F Log Chest.json")
Tracker:AddLocations("locations/Marine Temple 2F Stamp Station.json")
Tracker:AddLocations("locations/Marine Temple 3F NE Chest.json")
Tracker:AddLocations("locations/Marine Temple 3F Puzzle Chest.json")
Tracker:AddLocations("locations/Marine Temple 3F Whip Chest.json")
Tracker:AddLocations("locations/Marine Temple 6F Boss Key.json")
Tracker:AddLocations("locations/Marine Temple 6F E Chest.json")
Tracker:AddLocations("locations/Marine Temple 6F W Chest.json")
Tracker:AddLocations("locations/Marine Temple Dungeon Reward.json")
Tracker:AddLocations("locations/Marine Temple Ferrus Force Gem.json")
Tracker:AddLocations("locations/Marine Temple Heart Container.json")
Tracker:AddLocations("locations/Marine Temple Song Statue.json")
Tracker:AddLocations("locations/Mayscore Buy Lumber.json")
Tracker:AddLocations("locations/Mayscore Deliver Steel.json")
Tracker:AddLocations("locations/Mayscore Pick Up Dovok.json")
Tracker:AddLocations("locations/Mayscore Pick Up Mash.json")
Tracker:AddLocations("locations/Mayscore Pick Up Morris.json")
Tracker:AddLocations("locations/Mayscore Pick Up Wood.json")
Tracker:AddLocations("locations/Mayscore Pick Up Yamahiko.json")
Tracker:AddLocations("locations/Mayscore Shop Postcards.json")
Tracker:AddLocations("locations/Mayscore Shop Red Potion.json")
Tracker:AddLocations("locations/Mayscore Shop Shield.json")
Tracker:AddLocations("locations/Mayscore Shop Treasure 1.json")
Tracker:AddLocations("locations/Mayscore Shop Treasure 2.json")
Tracker:AddLocations("locations/Mayscore Stamp Station.json")
Tracker:AddLocations("locations/Mayscore Whip Chest.json")
Tracker:AddLocations("locations/Mayscore Whip Race 105-115.json")
Tracker:AddLocations("locations/Mayscore Whip Race 115-130.json")
Tracker:AddLocations("locations/Mayscore Whip Race Sub 105.json")
Tracker:AddLocations("locations/Mountain Temple 1F NE Chest.json")
Tracker:AddLocations("locations/Mountain Temple 1F Right Maze Chest.json")
Tracker:AddLocations("locations/Mountain Temple 2F Center Chest.json")
Tracker:AddLocations("locations/Mountain Temple 2F Heatoise Chest.json")
Tracker:AddLocations("locations/Mountain Temple 2F Left Chest.json")
Tracker:AddLocations("locations/Mountain Temple 2F NW Chest.json")
Tracker:AddLocations("locations/Mountain Temple 2F Stalfos.json")
Tracker:AddLocations("locations/Mountain Temple B1 Heatoise Chest.json")
Tracker:AddLocations("locations/Mountain Temple B1 Stamp Station.json")
Tracker:AddLocations("locations/Mountain Temple B2 NE Chest.json")
Tracker:AddLocations("locations/Mountain Temple B2 NW Chest.json")
Tracker:AddLocations("locations/Mountain Temple B2 SE Chest.json")
Tracker:AddLocations("locations/Mountain Temple B3 Boss Key.json")
Tracker:AddLocations("locations/Mountain Temple B3 N Chest.json")
Tracker:AddLocations("locations/Mountain Temple Boss Heart Container.json")
Tracker:AddLocations("locations/Mountain Temple Dungeon Reward.json")
Tracker:AddLocations("locations/Mountain Temple Song Statue.json")
Tracker:AddLocations("locations/Ocean Realm Shoot W Portal.json")
Tracker:AddLocations("locations/Outset Beach Tree Buried Chest.json")
Tracker:AddLocations("locations/Outset Bee Tree.json")
Tracker:AddLocations("locations/Outset Clear Rocks.json")
Tracker:AddLocations("locations/Outset Deliver Cuccos.json")
Tracker:AddLocations("locations/Outset Ferrus Force Gem.json")
Tracker:AddLocations("locations/Outset Niko 10 Stamps Reward.json")
Tracker:AddLocations("locations/Outset Niko 15 Stamps Reward.json")
Tracker:AddLocations("locations/Outset Niko 20 Stamps Reward.json")
Tracker:AddLocations("locations/Outset Niko Stamp Book.json")
Tracker:AddLocations("locations/Outset Nikos House Tree Buried Chest.json")
Tracker:AddLocations("locations/Outset Pick Up Joe.json")
Tracker:AddLocations("locations/Outset Stamp Station.json")
Tracker:AddLocations("locations/Papuzia Shop Arrows.json")
Tracker:AddLocations("locations/Papuzia Shop Bombs.json")
Tracker:AddLocations("locations/Papuzia Shop Postcards.json")
Tracker:AddLocations("locations/Papuzia Shop Purple Potion.json")
Tracker:AddLocations("locations/Papuzia Shop Yellow Potion.json")
Tracker:AddLocations("locations/Papuzia Village Buy Fish.json")
Tracker:AddLocations("locations/Papuzia Village Buy Vessel.json")
Tracker:AddLocations("locations/Papuzia Village Deliver Ice.json")
Tracker:AddLocations("locations/Papuzia Village NE Chest.json")
Tracker:AddLocations("locations/Papuzia Village Orcas Force Gem.json")
Tracker:AddLocations("locations/Papuzia Village Pick Up Carben.json")
Tracker:AddLocations("locations/Papuzia Village S Center Chest.json")
Tracker:AddLocations("locations/Papuzia Village SW Chest.json")
Tracker:AddLocations("locations/Papuzia Village Song Statue.json")
Tracker:AddLocations("locations/Papuzia Village Stamp Station.json")
Tracker:AddLocations("locations/Papuzia Village Wadatsumis Force Gem.json")
Tracker:AddLocations("locations/Pirate Hideout Minigame 3000-4000.json")
Tracker:AddLocations("locations/Pirate Hideout Minigame 4000-5000.json")
Tracker:AddLocations("locations/Pirate Hideout Minigame 5000+.json")
Tracker:AddLocations("locations/Pirate Hideout Pick Up Wadatsumi.json")
Tracker:AddLocations("locations/Pirate Hideout Secret Cave Left Treasure.json")
Tracker:AddLocations("locations/Pirate Hideout Secret Cave Mid Treasure.json")
Tracker:AddLocations("locations/Pirate Hideout Secret Cave Right Treasure.json")
Tracker:AddLocations("locations/Pirate Hideout Stamp Station.json")
Tracker:AddLocations("locations/Rabbit Central Blizzard.json")
Tracker:AddLocations("locations/Rabbit E Anouki Village.json")
Tracker:AddLocations("locations/Rabbit E Desert Temple.json")
Tracker:AddLocations("locations/Rabbit E Lost at Sea.json")
Tracker:AddLocations("locations/Rabbit E Mayscore.json")
Tracker:AddLocations("locations/Rabbit E Ocean.json")
Tracker:AddLocations("locations/Rabbit E Outset.json")
Tracker:AddLocations("locations/Rabbit E Pirate Hideout.json")
Tracker:AddLocations("locations/Rabbit E Sand Maze.json")
Tracker:AddLocations("locations/Rabbit E Sand Realm.json")
Tracker:AddLocations("locations/Rabbit Haven Island Chest.json")
Tracker:AddLocations("locations/Rabbit Haven Monas Force Gem.json")
Tracker:AddLocations("locations/Rabbit Haven Net Gift.json")
Tracker:AddLocations("locations/Rabbit Haven Rescue 1 of Each Rabbit.json")
Tracker:AddLocations("locations/Rabbit Haven Rescue 10 Grass Rabbits.json")
Tracker:AddLocations("locations/Rabbit Haven Rescue 10 Mountain Rabbits.json")
Tracker:AddLocations("locations/Rabbit Haven Rescue 10 Ocean Rabbits.json")
Tracker:AddLocations("locations/Rabbit Haven Rescue 10 Sand Rabbits.json")
Tracker:AddLocations("locations/Rabbit Haven Rescue 10 Snow Rabbits.json")
Tracker:AddLocations("locations/Rabbit Haven Rescue 10 of Each Rabbit.json")
Tracker:AddLocations("locations/Rabbit Haven Rescue 5 Rabbits.json")
Tracker:AddLocations("locations/Rabbit Mid Sand Maze.json")
Tracker:AddLocations("locations/Rabbit N Fire Glyph.json")
Tracker:AddLocations("locations/Rabbit N Icy Spring Station.json")
Tracker:AddLocations("locations/Rabbit N Lost at Sea.json")
Tracker:AddLocations("locations/Rabbit N Marine Temple.json")
Tracker:AddLocations("locations/Rabbit N Mountain.json")
Tracker:AddLocations("locations/Rabbit N Sand Realm.json")
Tracker:AddLocations("locations/Rabbit N Undersea Entrance.json")
Tracker:AddLocations("locations/Rabbit NE Blizzard.json")
Tracker:AddLocations("locations/Rabbit NE Mountain.json")
Tracker:AddLocations("locations/Rabbit NW Blizzard.json")
Tracker:AddLocations("locations/Rabbit NW Mountain.json")
Tracker:AddLocations("locations/Rabbit Near Castle Town.json")
Tracker:AddLocations("locations/Rabbit Near Disorientation Station.json")
Tracker:AddLocations("locations/Rabbit Near Ends of the Earth.json")
Tracker:AddLocations("locations/Rabbit Near Goron Target Range.json")
Tracker:AddLocations("locations/Rabbit Near Island Sanctuary.json")
Tracker:AddLocations("locations/Rabbit Near Ocean Portal.json")
Tracker:AddLocations("locations/Rabbit Near Ocean Shortcut.json")
Tracker:AddLocations("locations/Rabbit Near Rabbit Haven.json")
Tracker:AddLocations("locations/Rabbit Near Snowdrift Station.json")
Tracker:AddLocations("locations/Rabbit Near ToS Fire Realm.json")
Tracker:AddLocations("locations/Rabbit Near Wooded Temple.json")
Tracker:AddLocations("locations/Rabbit Past Wooden Bridge.json")
Tracker:AddLocations("locations/Rabbit S Mountain.json")
Tracker:AddLocations("locations/Rabbit S Rabbit Haven.json")
Tracker:AddLocations("locations/Rabbit S Sand Realm.json")
Tracker:AddLocations("locations/Rabbit S Undersea Entrance.json")
Tracker:AddLocations("locations/Rabbit SE Blizzard.json")
Tracker:AddLocations("locations/Rabbit SE Mountain.json")
Tracker:AddLocations("locations/Rabbit SW Blizzard.json")
Tracker:AddLocations("locations/Rabbit SW Rabbit Haven.json")
Tracker:AddLocations("locations/Rabbit SW Trading Post.json")
Tracker:AddLocations("locations/Rabbit Sand Valley.json")
Tracker:AddLocations("locations/Rabbit W Anouki Village.json")
Tracker:AddLocations("locations/Rabbit W Desert Temple.json")
Tracker:AddLocations("locations/Rabbit W Icy Spring Station.json")
Tracker:AddLocations("locations/Rabbit W Pirate Hideout.json")
Tracker:AddLocations("locations/Rabbit W Sand Maze.json")
Tracker:AddLocations("locations/Rabbit W Sand Realm.json")
Tracker:AddLocations("locations/Sand Realm Shoot Temple Portal.json")
Tracker:AddLocations("locations/Slippery Station Amateur Reward.json")
Tracker:AddLocations("locations/Slippery Station Champion Reward.json")
Tracker:AddLocations("locations/Slippery Station Pro Reward.json")
Tracker:AddLocations("locations/Snow Realm Pick Up Ferrus.json")
Tracker:AddLocations("locations/Snow Realm Shoot Bridge Portal.json")
Tracker:AddLocations("locations/Snow Realm Shoot N Portal.json")
Tracker:AddLocations("locations/Snow Realm Shoot SW Portal.json")
Tracker:AddLocations("locations/Snowdrift Station Puzzle Reward.json")
Tracker:AddLocations("locations/Snowfall Sanctuary Deliver Vessel.json")
Tracker:AddLocations("locations/Snowfall Sanctuary Song of Restoration.json")
Tracker:AddLocations("locations/Snowfall Sanctuary Stamp Station.json")
Tracker:AddLocations("locations/Snowfall Sanctuary Steem Gift With Snow Source.json")
Tracker:AddLocations("locations/Snowfall Supermarket Heart Container.json")
Tracker:AddLocations("locations/Snowfall Supermarket Postcards.json")
Tracker:AddLocations("locations/Snowfall Supermarket Purple Potion.json")
Tracker:AddLocations("locations/Snowfall Supermarket Red Potion.json")
Tracker:AddLocations("locations/Snowfall Supermarket Shield.json")
Tracker:AddLocations("locations/Snowfall Supermarket Treasure.json")
Tracker:AddLocations("locations/Snurglars Gold Key.json")
Tracker:AddLocations("locations/Snurglars Orange Key.json")
Tracker:AddLocations("locations/Snurglars Purple Key.json")
Tracker:AddLocations("locations/ToS 10F Boss Key.json")
Tracker:AddLocations("locations/ToS 10F NW Chest.json")
Tracker:AddLocations("locations/ToS 11F Chest.json")
Tracker:AddLocations("locations/ToS 12F Ocean Rail Glyph.json")
Tracker:AddLocations("locations/ToS 13F Central Tear of Light.json")
Tracker:AddLocations("locations/ToS 13F E Swing Chest.json")
Tracker:AddLocations("locations/ToS 13F N Chest.json")
Tracker:AddLocations("locations/ToS 13F SE Raised Chest.json")
Tracker:AddLocations("locations/ToS 13F SE Tear of Light.json")
Tracker:AddLocations("locations/ToS 13F SW Raised Chest.json")
Tracker:AddLocations("locations/ToS 14F SE Chest.json")
Tracker:AddLocations("locations/ToS 14F Tear of Light.json")
Tracker:AddLocations("locations/ToS 15F NE Chest.json")
Tracker:AddLocations("locations/ToS 16F Bombable Wall Chest.json")
Tracker:AddLocations("locations/ToS 17F Fire Rail Glyph.json")
Tracker:AddLocations("locations/ToS 18F Center Chest.json")
Tracker:AddLocations("locations/ToS 18F N Chest.json")
Tracker:AddLocations("locations/ToS 18F SE Tear of Light.json")
Tracker:AddLocations("locations/ToS 18F SW Chest.json")
Tracker:AddLocations("locations/ToS 19F Center E Chest.json")
Tracker:AddLocations("locations/ToS 19F Center W Chest.json")
Tracker:AddLocations("locations/ToS 19F S Tear of Light.json")
Tracker:AddLocations("locations/ToS 1F Chest.json")
Tracker:AddLocations("locations/ToS 1F E Tear of Light.json")
Tracker:AddLocations("locations/ToS 1F N Tear of Light.json")
Tracker:AddLocations("locations/ToS 1F W Tear of Light.json")
Tracker:AddLocations("locations/ToS 20F SW Tear of Light.json")
Tracker:AddLocations("locations/ToS 21F Bomb Wall Chest.json")
Tracker:AddLocations("locations/ToS 22F Boss Key.json")
Tracker:AddLocations("locations/ToS 23F Defeat Staven.json")
Tracker:AddLocations("locations/ToS 24F Final Chest.json")
Tracker:AddLocations("locations/ToS 28F E Raised Chest.json")
Tracker:AddLocations("locations/ToS 28F W Raised Chest.json")
Tracker:AddLocations("locations/ToS 29F SE Chest.json")
Tracker:AddLocations("locations/ToS 2F Bomb Wall Chest.json")
Tracker:AddLocations("locations/ToS 2F Raised Chest.json")
Tracker:AddLocations("locations/ToS 2F Whirlwind Chest.json")
Tracker:AddLocations("locations/ToS 30F SE Wrecker Chest.json")
Tracker:AddLocations("locations/ToS 30F W Chest.json")
Tracker:AddLocations("locations/ToS 3F Forest Rail Glyph.json")
Tracker:AddLocations("locations/ToS 4F Central Chest.json")
Tracker:AddLocations("locations/ToS 4F E Tear of Light.json")
Tracker:AddLocations("locations/ToS 4F Lava Tear.json")
Tracker:AddLocations("locations/ToS 4F NE Chest.json")
Tracker:AddLocations("locations/ToS 4F W Tear of Light.json")
Tracker:AddLocations("locations/ToS 5F Bomb Wall Chest.json")
Tracker:AddLocations("locations/ToS 5F Island Chest.json")
Tracker:AddLocations("locations/ToS 5F Spinnit Key.json")
Tracker:AddLocations("locations/ToS 6F Enemy Big Chest.json")
Tracker:AddLocations("locations/ToS 6F Enemy Chest 1.json")
Tracker:AddLocations("locations/ToS 6F Enemy Chest 2.json")
Tracker:AddLocations("locations/ToS 6F Enemy Chest 3.json")
Tracker:AddLocations("locations/ToS 6F Key.json")
Tracker:AddLocations("locations/ToS 7F Snow Rail Glyph.json")
Tracker:AddLocations("locations/ToS 8F N Bombable Wall Chest.json")
Tracker:AddLocations("locations/ToS 8F S Bombable Wall Chest.json")
Tracker:AddLocations("locations/ToS 9F NE Bombable Wall Tear.json")
Tracker:AddLocations("locations/ToS 9F NE Tear of Light.json")
Tracker:AddLocations("locations/ToS 9F NW Secret Chest.json")
Tracker:AddLocations("locations/ToS 9F NW Tear of Light.json")
Tracker:AddLocations("locations/ToS Summit Stamp Station.json")
Tracker:AddLocations("locations/Trading Post Buried Chest.json")
Tracker:AddLocations("locations/Trading Post Buy Shield.json")
Tracker:AddLocations("locations/Trading Post Deliver Dark Ore.json")
Tracker:AddLocations("locations/Trading Post Pick Up Kenzo.json")
Tracker:AddLocations("locations/Trading Post Repair Bridge.json")
Tracker:AddLocations("locations/Trading Post Song Statue.json")
Tracker:AddLocations("locations/Trading Post Stamp Station.json")
Tracker:AddLocations("locations/Tunnel to ToS 1F Block Chest.json")
Tracker:AddLocations("locations/Tunnel to ToS 2F Chest.json")
Tracker:AddLocations("locations/Tunnel to Valley Sanctuary Chest.json")
Tracker:AddLocations("locations/Valley Sanctuary NW Chest.json")
Tracker:AddLocations("locations/Valley Sanctuary Song of Restoration.json")
Tracker:AddLocations("locations/Valley Sanctuary Stamp Station.json")
Tracker:AddLocations("locations/Wooded Temple 1F Enemy Chest.json")
Tracker:AddLocations("locations/Wooded Temple 1F Key.json")
Tracker:AddLocations("locations/Wooded Temple 1F Stamp Station.json")
Tracker:AddLocations("locations/Wooded Temple 1F Switch Chest.json")
Tracker:AddLocations("locations/Wooded Temple 2F Enemy Chest.json")
Tracker:AddLocations("locations/Wooded Temple 2F Poison Chest.json")
Tracker:AddLocations("locations/Wooded Temple 3F Boss Key.json")
Tracker:AddLocations("locations/Wooded Temple 3F Chestnut Chest.json")
Tracker:AddLocations("locations/Wooded Temple 3F SE Chest.json")
Tracker:AddLocations("locations/Wooded Temple Boss Heart Container.json")
Tracker:AddLocations("locations/Wooded Temple Dungeon Reward.json")
Tracker:AddLocations("locations/Wooded Temple Song Statue.json")
Tracker:AddLocations("locations/Woodland Sanctuary Chest.json")
Tracker:AddLocations("locations/Woodland Sanctuary Song Statue.json")
Tracker:AddLocations("locations/Woodland Sanctuary Song of Restoration.json")
Tracker:AddLocations("locations/Woodland Sanctuary Stamp Station.json")
Tracker:AddLocations("locations/Overworld.json")
