ITEM_MAPPING = {
	[30] = {{"portal_a_sr", "toggle"}},
	[31] = {{"portal_c_sr", "toggle"}},
	[32] = {{"portal_h_e", "toggle"}},
	[33] = {{"portal_f_mr", "toggle"}},
	[34] = {{"portal_e_fr", "toggle"}},
	[35] = {{"portal_d", "toggle"}},
	[36] = {{"portal_g_fr", "toggle"}},
	[37] = {{"portal_c_sr", "toggle"}},

	[38] = {{"forest_glyph", "toggle"}},
	[39] = {{"snow_glyph", "toggle"}},
	[40] = {{"ocean_glyph", "toggle"}},
	[41] = {{"fire_glyph", "toggle"}},
	[42] = {{"wtt", "toggle"}},
	[43] = {{"btt", "toggle"}},
	[44] = {{"oct", "toggle"}},
	[45] = {{"mtt", "toggle"}},
	[46] = {{"dtt", "toggle"}},
	[47] = {{"snowdrift", "toggle"}},
	[48] = {{"slippery", "toggle"}},
	[49] = {{"pirate", "toggle"}},
	[50] = {{"las", "toggle"}},
	[51] = {{"ocean_shortcut", "toggle"}},
	[52] = {{"mayscore_bridge", "toggle"}},
	[53] = {{"tp_portal", "toggle"}},
	[54] = {{"w_castle", "toggle"}},
	[55] = {{"w_forest", "toggle"}},
	[56] = {{"cave", "toggle"}},
	[57] = {{"w_wt", "toggle"}},
	[58] = {{"n_castle", "toggle"}},
	[59] = {{"snow_bridge", "toggle"}},
	[60] = {{"nicyspring", "toggle"}},
	[61] = {{"ocean_portal", "toggle"}},

	[62] = {{"sandrealmtracks", "toggle"}},

	[63] = {{"firerealmsandportaltracks", "toggle"}},
	[64] = {{"darkoreminetracks", "toggle"}},
	[65] = {{"endsoftheearthtracks", "toggle"}},
	[66] = {{"disorientationstationtracks", "toggle"}},
	[67] = {{"snowrealmgorgetracks", "toggle"}},

	[68] = {{"forest_source", "toggle"}},
	[69] = {{"snow_source", "toggle"}},
	[70] = {{"ocean_source", "toggle"}},
	[71] = {{"fire_source", "toggle"}},
	[72] = {{"sandsource", "toggle"}},

	[161] = {{"SnurglarKeys", "toggle"}},
	[165] = {{"SnurglarKeys", "toggle"}},

	[192] = {{"Tower of Spirits Base", "toggle"}},

	[248] = {{"westernforesttracks", "toggle"}},
	[249] = {{"anoukivillagetracks", "toggle"}},
	[250] = {{"thawlandtracks", "toggle"}},
	[251] = {{"blizzardtracks", "toggle"}},
	[252] = {{"castletracks", "toggle"}},
	[253] = {{"woodlandtracks", "toggle"}},
	[254] = {{"borderlandstracks", "toggle"}},
	[255] = {{"coastaltracks", "toggle"}},
	[256] = {{"piratetracks", "toggle"}},
	[257] = {{"oceantracks", "toggle"}},
	[258] = {{"islandtracks", "toggle"}},
	[259] = {{"valleytracks", "toggle"}},
	[260] = {{"mountaintracks", "toggle"}},
	[261] = {{"aridtracks", "toggle"}},
	[262] = {{"dunetracks", "toggle"}},
	[263] = {{"towertracks", "toggle"}},
	[264] = {{"completedforestglyph", "toggle"}},
	[265] = {{"majorforesttracks", "toggle"}},
	[266] = {{"minorforesttracks", "toggle"}},
	[267] = {{"completedsnowglyph", "toggle"}},
	[268] = {{"majorsnowtracks", "toggle"}},
	[269] = {{"minorsnowtracks", "toggle"}},
	[270] = {{"completedoceanglyph", "toggle"}},
	[271] = {{"majoroceantracks", "toggle"}},
	[272] = {{"minoroceantracks", "toggle"}},
	[273] = {{"completedfireglyph", "toggle"}},
	[274] = {{"majorfiretracks", "toggle"}},
	[275] = {{"minorfiretracks", "toggle"}},
	[276] = {{"completeddeserttracks", "toggle"}},
	[277] = {{"majordeserttracks", "toggle"}},
	[278] = {{"minordeserttracks", "toggle"}}
}